site_name: xDrip4iOS
theme: readthedocs
extra_css:
    - css/admonitions.css
    - css/extra.css
markdown_extensions:
    - admonition
    - toc:
        permalink: ⌁

pages:
- 'Introduction': 'index.md'
- 'FAQ': 'faq.md'
- Install: 
    - 'Install from Testflight': 'install/testflight.md'
    - 'Build from Source': 'install/build.md'
    - 'How Do I Release?': 'install/personal_testflight.md'
- Connect:
    - 'Initial Configuration': 'connect/index.md'
    - 'Connect to CGM as a Master': 'connect/cgm.md'
    - 'Connect to Nightscout as a Follower': 'connect/follower.md'
    - 'Connect to M5Stack/M5StickC': 'connect/devices.md'
- Configure/Using:
    - 'Home Screen' : 'configure/homeview.md'
    - 'General': 'configure/index.md'
    - 'Alarms': 'configure/alarms.md'
    - 'Calibration': 'configure/calibrate.md'
    - 'Treatments': 'configure/treatments.md'
    - 'Apple Watch': 'configure/applewatch.md'
    - 'Other Smartwatches': 'configure/smartwatches.md'
- Advanced:
    - 'FreeAPS (Loop) Integration': 'advanced/freeaps.md'
    - 'FreeAPS X (OpenAPS) Integration': 'advanced/freeapsx.md'
- Troubleshoot:
    - 'Troubleshooting': 'troubleshoot/index.md'
    - 'Cannot Connect?': 'troubleshoot/connection_troubles.md'
    - 'Disconnections?': 'troubleshoot/disconnections.md'
    - 'How to Report Errors': 'troubleshoot/reporting.md'
